=== bleroy/ajaxdoc/Projects/ScriptDocProject.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="project">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="scripts">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="script">
                <xs:complexType>
                  <xs:attribute name="assembly" type="xs:string" use="optional" />
                  <xs:attribute name="name" type="xs:string" use="optional" />
                  <xs:attribute name="path" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="namespaces">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="namespace" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="singletons">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="singleton">
                <xs:complexType mixed="true">
                  <xs:attribute name="name" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bleroy/ajaxdoc/Projects/MicrosoftAjax.project.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- This project documents the Atlas framework itself. -->
<project xmlns:scriptdoc="http://www.w3.org/2001/XMLSchema-instance"
  scriptdoc:noNamespaceSchemaLocation="ScriptDocProject.xsd">
  <scripts>
    <!-- <script assembly="FullyQualifiedAssemblyName" name="ResourceName" /> -->
    <!-- <script path="path/to/the/script.js" /> -->
    <script name="MicrosoftAjax.js"/>
    <script name="MicrosoftAjaxWebForms.js"/>
  </scripts>
  <namespaces>
    <namespace></namespace>
    <namespace>Sys</namespace>
    <namespace>Sys.Net</namespace>
    <namespace>Sys.Serialization</namespace>
    <namespace>Sys.Services</namespace>
    <namespace>Sys.UI</namespace>
    <namespace>Sys.WebForms</namespace>
  </namespaces>
  <singletons>
    <singleton>Sys.Application</singleton>
    <singleton>Sys.Debug</singleton>
    <singleton>Sys.Net.WebRequestManager</singleton>
    <singleton>Sys.Services.AuthenticationService</singleton>
    <singleton>Sys.Services.ProfileService</singleton>
    <singleton>Sys.Services.RoleService</singleton>
  </singletons>
</project>
